GCN_configs_q:
  0:
    in_features: 512
    out_features: 4096
    nbaselayer: 1
    aggrmethod: nores
    withbn: True
    withloop: False
    withweight: True
    bias: True
    activation_type: softmax
    dropout: 0.0
    dense: False
  1:
    in_features: 4096
    out_features: 512
    nbaselayer: 1
    aggrmethod: nores
    withbn: False
    withloop: False
    withweight: True
    bias: True
    activation_type: identity
    dropout: 0.0
    dense: False

GCN_configs_t:
  0:
    in_features: 512
    out_features: 512
    nbaselayer: 1
    aggrmethod: nores
    withbn: False
    withloop: False
    withweight: False
    bias: False
    activation_type: identity
    dropout: 0.0
    dense: False
